# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ..Base import (
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_1,
)


class MethodSpec(MethodSpec_1):
    kind: Literal["yeast"] = "yeast"
    significance_level: float
    expected_num_observations: int
    estimated_variance: float = Field(
        ...,
        description="The estimated variance of a single increment (difference).\nIf not specified, conservatively defaults to the max variance for a difference of two Binomials (0.5).",
    )


class Protocol(Protocol_1):
    task: TaskSpec
    method: MethodSpec


class TaskSpec(TaskSpec_1):
    kind: Literal["yeast"] = "yeast"
    arms: list[str]
