# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import Field

from ..Base import Log


class Boundary(Log):
    value: float | None = None


class DecisionStatus(StrEnum):
    """
    Status of an ongoing or completed YEAST Test.
    """

    CONTINUE_ = "continue"
    STOP_EFFICACY = "stop_efficacy"
    STOP_PLAN_END_REACHED = "stop_plan_end_reached"
    STOP = "stop"


class LookResult(Log):
    """
    Result of a statistical test/evaluation for the study at a look (YEAST).
    """

    sample_n: int = Field(..., description="Total number of samples (cumulative).")
    info_frac: float = Field(..., description="Fraction of information accrued.")
    trajectory: float = Field(
        ..., description="The calculated trajectory value (Your Evidence)."
    )
    raw_difference: float | None = Field(
        None,
        description="The raw difference (sum of successes/values difference) before normalization.",
    )
    efficacy_boundary: float | None = Field(
        None, description="The efficacy boundary at this look."
    )
    is_efficacy_crossed: bool = Field(
        ..., description="Whether the trajectory crossed the efficacy boundary."
    )
    status: DecisionStatus | str = Field(
        ..., description="Current status of the YEAST test."
    )
