# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import Field

from ..Base import Log


class Boundary(Log):
    value: float | None = None


class DecisionStatus(StrEnum):
    """
    Status of an ongoing or completed YEAST Test.
    """

    CONTINUE_ = "continue"
    STOP_EFFICACY = "stop_efficacy"
    STOP_PLAN_END_REACHED = "stop_plan_end_reached"
    STOP = "stop"


class LookResult(Log):
    """
    Result of a statistical test/evaluation for the study at a look.
    """

    sample_n: int
    info_frac: float
    trajectory: float = Field(..., description="The calculated trajectory value")
    efficacy_boundary: float | None = None
    is_efficacy_crossed: bool
    status: DecisionStatus | str
