name: earlysign_sdk
prefixes:
  linkml: https://w3id.org/linkml/
  base: https://earlysign.io/schema/ES3/base
  avi: https://earlysign.io/schema/ES3/avi
  gst: https://earlysign.io/schema/ES3/group_sequential
  yeast: https://earlysign.io/schema/ES3/yeast

import_map:
  https://earlysign.io/schema/ES3/base: earlysign.schema.ES3.Base
  https://earlysign.io/schema/ES3/avi: earlysign.builtin.AVI.AVI
  https://earlysign.io/schema/ES3/group_sequential: earlysign.builtin.group_sequential.group_sequential
  https://earlysign.io/schema/ES3/yeast: earlysign.builtin.YEAST.YEAST

# In gen-project, we list schemas to generate
# Using --no-mergeimports at the CLI later
schemas:
  - earlysign/schema/ES3/base.yaml
  - earlysign/builtin/AVI/schema.yaml
  - earlysign/builtin/group_sequential/schema.yaml
  - earlysign/builtin/YEAST/schema.yaml
