# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

from ..Base import (
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_1,
)


class AVIMetadata(BaseModel):
    version: str = Field(..., description="Metadata version")


class BaseAVIMethodSpec(MethodSpec_1):
    pass


class GAVIMethodSpec(BaseAVIMethodSpec):
    kind: Literal["GAVI"] = "GAVI"
    alpha: float = Field(..., description="Significance level.")
    variance: float | None = Field(
        None,
        description="Estimated variance (sigma squared).\nIf null, the variance is estimated from the data (Maharaj et al., 2023).",
    )
    sides: Sides = Field(..., description="One-sided or two-sided test.")
    max_n: int = Field(
        ..., description="Maximum sample size, used for rho calculation."
    )


class MSPRTMethodSpec(BaseAVIMethodSpec):
    kind: Literal["mSPRT"] = "mSPRT"
    alpha: float = Field(..., description="Significance level.")
    variance: float | None = Field(
        None,
        description="Estimated variance (sigma squared).\nIf null, the variance is estimated from the data (Maharaj et al., 2023).",
    )
    sides: Sides = Field(..., description="One-sided or two-sided test.")
    mde: float = Field(
        ...,
        description="Minimum Detectable Effect (absolute difference), used for phi calculation.",
    )


class Protocol(Protocol_1):
    task: TaskSpec
    method: MethodSpec


class ResponseType(StrEnum):
    BINARY = "binary"
    CONTINUOUS = "continuous"


class SequentialQuantileMethodSpec(BaseAVIMethodSpec):
    kind: Literal["SequentialQuantile"] = "SequentialQuantile"
    quantile: float = Field(..., description="Target quantile (e.g., 0.5 for median).")
    alpha: float = Field(..., description="Significance level.")
    max_n: int | None = Field(
        None, description="Optional maximum sample size for the horizon."
    )


MethodSpec = TypeAliasType(
    "MethodSpec", GAVIMethodSpec | MSPRTMethodSpec | SequentialQuantileMethodSpec
)


class Sides(StrEnum):
    """
    One-sided or two-sided test.
    """

    ONE = "one"
    TWO = "two"


class TaskSpec(TaskSpec_1):
    kind: Literal["AVI"] = "AVI"
    arms: list[str]
    response_type: ResponseType
