# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import Field

from ..Base import Log


class DecisionStatus(StrEnum):
    CONTINUE_ = "continue"
    STOP_DETECTED = "stop_detected"
    STOP_PLAN_END_REACHED = "stop_plan_end_reached"


class LookResult(Log):
    sample_n: int = Field(
        ..., description="The total sample size (cumulative) at this look."
    )
    trajectory: float = Field(..., description="The calculated trajectory statistic.")
    boundary: float = Field(..., description="The current boundary value.")
    is_crossed: bool = Field(
        ..., description="Whether the trajectory crossed the boundary."
    )
    status: DecisionStatus | str = Field(
        ..., description="The decision status after this look."
    )


class SequentialQuantileLookResult(Log):
    """
    Result of a sequential quantile test look.
    """

    sample_n: int = Field(..., description="Current cumulative sample size.")
    estimated_quantile: float = Field(
        ..., description="Point estimate of the target quantile."
    )
    interval_lower: float = Field(..., description="Lower confidence bound.")
    interval_upper: float = Field(..., description="Upper confidence bound.")
    status: DecisionStatus | str = Field(..., description="Current status of the test.")
