# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import Field

from ..Base import Log


class DecisionStatus(StrEnum):
    CONTINUE_ = "continue"
    STOP_EFFICACY = "stop_efficacy"
    STOP_PLAN_END_REACHED = "stop_plan_end_reached"


class LookResult(Log):
    sample_n: int = Field(
        ..., description="The total sample size (cumulative) at this look."
    )
    trajectory: float = Field(..., description="The calculated trajectory statistic.")
    boundary: float = Field(..., description="The current boundary value.")
    is_crossed: bool = Field(
        ..., description="Whether the trajectory crossed the boundary."
    )
    status: DecisionStatus | str = Field(
        ..., description="The decision status after this look."
    )


class SequentialQuantileLookResult(Log):
    sample_n: int
    estimated_quantile: float
    interval_lower: float
    interval_upper: float
    status: DecisionStatus | str
