# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Literal

from .Base import (
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_1,
)


class MethodSpec(MethodSpec_1):
    kind: Literal["e_process"] = "e_process"
    growth_rate: float | None = None


class TaskSpec(TaskSpec_1):
    kind: Literal["anytime_valid"] = "anytime_valid"
    null_p: float
    alt_p: float | None = None
    alpha: float


class Protocol(Protocol_1):
    task: TaskSpec
    method: MethodSpec
