# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class Log(BaseModel):
    """
    Base log/event model for metadata inclusion.
    """

    ES3_version: str | None = Field("v1.0.0", description="Schema version")


class Metadata(BaseModel):
    """
    Metadata for EarlySign events and records.
    """

    ES3_version: str | None = Field(
        "v1.0.0", description='Schema version (e.g., "v1.0.0")'
    )


class MethodSpec(BaseModel):
    """
    Base class for Operational Method.
    Concrete protocols should extend this (e.g., GST.MethodSpec).
    """

    kind: str = Field(..., description="The kind of method (discriminator).")


class Protocol(BaseModel):
    """
    The Root Protocol Container.
    Defines the high-level structure of any EarlySign protocol.
    """

    ES3_version: str | None = Field("v1.0.0", description="Schema version")
    name: str = Field(..., description="The name of the protocol.")
    task: TaskSpec = Field(..., description="The problem definition.")
    method: MethodSpec = Field(..., description="The operational method.")


class TaskSpec(BaseModel):
    """
    Base class for Problem Definition.
    Concrete protocols should extend this (e.g., GST.TaskSpec).
    """

    kind: str = Field(..., description="The kind of task (discriminator).")
