# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class Log(BaseModel):
    """
    Base log/event model for versioning.
    Can be extended by log/event models that need version tracking.
    """

    ES3_version: str | None = Field("v1.0.0", description="Schema version")


class Metadata(BaseModel):
    """
    Metadata for EarlySign events and records.
    Can be used to track schema version at the Ledger/event level.
    """

    ES3_version: str | None = Field("v1.0.0", description="Schema version")


class MethodSpec(BaseModel):
    """
    Base class for Operational Method.
    Concrete protocols should extend this (e.g., GST.MethodSpec).
    """

    kind: str


class TaskSpec(BaseModel):
    """
    Base class for Problem Definition.
    Concrete protocols should extend this (e.g., GST.TaskSpec).
    """

    kind: str


class Protocol(BaseModel):
    """
    The Root Protocol Container.
    Defines the high-level structure of any EarlySign protocol.
    """

    ES3_version: str | None = Field("v1.0.0", description="Schema version")
    name: str
    task: TaskSpec
    method: MethodSpec
