# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field

from .Base import Log


class ArmMetrics(BaseModel):
    """
    Standard statistics for a single arm (Bernoulli/Binomial).
    """

    total: int = Field(..., description="Total number of trials.")
    successes: int = Field(..., description="Total number of successes.")
    p_hat: float = Field(..., description="Success probability estimate (p-hat).")


class ArmStatus(BaseModel):
    """
    Latest status and metrics for a single arm.
    """

    metrics: ArmMetrics
    is_active: bool


class BinomialArmData(Log):
    """
    Raw evidence: data for a single arm (Binomial).
    """

    total: int = Field(..., description="Total number of trials.")
    success: int = Field(..., description="Total number of successes.")
    arm: str = Field(..., description="The name/id of the arm.")


class Scoreboard(BaseModel):
    """
    Collective state of all arms (Scoreboard).
    """

    arms: dict[str, ArmStatus]
