# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel

from .Base import Log


class ArmData(Log):
    """
    Raw evidence: data for a single arm.
    """

    n: int
    success: int
    arm: str


class ArmMetrics(BaseModel):
    """
    Standard statistics for a single arm (Bernoulli/Binomial).
    """

    n: int
    successes: int
    p_hat: float


class ArmStatus(BaseModel):
    """
    Latest status and metrics for a single arm.
    """

    metrics: ArmMetrics
    is_active: bool


class Scoreboard(BaseModel):
    """
    Collective state of all arms (Scoreboard).
    """

    arms: dict[str, ArmStatus]
