# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field

from .Base import Log


class ArmData(Log):
    """
    Raw evidence: aggregated data for a single arm (continuous).
    """

    n: int = Field(..., description="Sample size.")
    sum_x: float = Field(..., description="Sum of observations.")
    sum_x2: float = Field(..., description="Sum of squared observations.")
    arm: str = Field(..., description="Arm identifier.")


class ArmMetrics(BaseModel):
    """
    Standard statistics for a single arm (Continuous).
    """

    n: int
    mean: float
    variance: float


class ArmStatus(BaseModel):
    """
    Latest status and metrics for a single arm.
    """

    metrics: ArmMetrics
    is_active: bool


class Observation(Log):
    """
    Raw evidence: data for a single arm (continuous observation).
    """

    value: float = Field(..., description="The observed value.")
    arm: str = Field(..., description="Arm identifier.")


class Scoreboard(BaseModel):
    """
    Collective state of all arms (Scoreboard).
    """

    arms: dict[str, ArmStatus] = Field(..., description="Map of arm IDs to status.")
