# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel

from .Base import Log


class ArmData(Log):
    """
    Raw evidence: aggregated data for a single arm (continuous).
    """

    n: int
    sum_x: float
    sum_x2: float
    arm: str


class ArmMetrics(BaseModel):
    """
    Standard statistics for a single arm (Continuous).
    """

    n: int
    mean: float
    variance: float


class ArmStatus(BaseModel):
    """
    Latest status and metrics for a single arm.
    """

    metrics: ArmMetrics
    is_active: bool


class Observation(Log):
    """
    Raw evidence: data for a single arm (continuous observation).
    """

    value: float
    arm: str


class Scoreboard(BaseModel):
    """
    Collective state of all arms (Scoreboard).
    """

    arms: dict[str, ArmStatus]
