# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field

from .Base import Log


class ArmMetrics(Log):
    """
    Metrics for a single arm in a sequential quantile test.
    """

    total: int = Field(..., description="Sample size n at the time of calculation.")
    ci_lower: float = Field(
        ..., description="The value of the lower confidence bound (X at rank L_t)."
    )
    ci_upper: float = Field(
        ..., description="The value of the upper confidence bound (X at rank U_t)."
    )
    quantile_estimate: float = Field(
        ..., description="The point estimate of the target quantile."
    )


class ArmStatus(BaseModel):
    """
    Status wrapper for arm metrics.
    """

    metrics: ArmMetrics
    is_active: bool


class Scoreboard(BaseModel):
    """
    Projection of all arm metrics in a sequential quantile test.
    """

    arms: dict[str, ArmStatus]
