# Auto-generated by earlysign.parts.codegen.linkml_generator
# DO NOT EDIT MANUALLY
from typing import ClassVar, Literal, Optional

from pydantic import (
    Field,
)

from earlysign.schema.ES3.Base import (
    ArmMetrics as ArmMetrics,
    ArmStatus as ArmStatus,
    ArmStructure as ArmStructure,
    ArmStructureBase as ArmStructureBase,
    ConfiguredBaseModel as ConfiguredBaseModel,
    LinkMLMeta as LinkMLMeta,
    Log as Log,
    LookResult as LookResult,
    Metadata as Metadata,
    MethodSpec as MethodSpec,
    MultiArmComparison as MultiArmComparison,
    Protocol as Protocol,
    Scoreboard as Scoreboard,
    SingleArm as SingleArm,
    TaskSpec as TaskSpec,
    TwoArmComparison as TwoArmComparison,
)
from earlysign.schema.ES3.Binomial import (
    BinomialArmData as BinomialArmData,
    BinomialArmMetrics as BinomialArmMetrics,
    ExactBinomialModel as ExactBinomialModel,
)

metamodel_version = "1.7.0"
version = "None"


class YeastMethodSpec(MethodSpec):
    """
    MethodSpec for YEAST.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/yeast"}
    )

    kind: Literal["YEAST"] = Field(
        default="YEAST",
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "TaskSpec",
                    "MethodSpec",
                    "ArmStructureBase",
                    "SingleArm",
                    "TwoArmComparison",
                    "MultiArmComparison",
                    "ExactBinomialModel",
                    "YeastMethodSpec",
                    "YeastTaskSpec",
                ],
                "equals_string": "YEAST",
                "ifabsent": "string(YEAST)",
            }
        },
    )
    alpha: float = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastMethodSpec"]}},
    )
    mde: float = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastMethodSpec"]}},
    )
    significance_level: Optional[float] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastMethodSpec"]}},
    )
    expected_num_observations: Optional[int] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastMethodSpec"]}},
    )
    estimated_variance: Optional[float] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastMethodSpec"]}},
    )
    boundary_sequence: Optional[list[float]] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastMethodSpec"]}},
    )


class YeastTaskSpec(TaskSpec):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/yeast"}
    )

    kind: Literal["yeast"] = Field(
        default="yeast",
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "TaskSpec",
                    "MethodSpec",
                    "ArmStructureBase",
                    "SingleArm",
                    "TwoArmComparison",
                    "MultiArmComparison",
                    "ExactBinomialModel",
                    "YeastMethodSpec",
                    "YeastTaskSpec",
                ],
                "equals_string": "yeast",
                "ifabsent": "string(yeast)",
            }
        },
    )
    arms: ArmStructure = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {"domain_of": ["Scoreboard", "YeastTaskSpec"]}
        },
    )


class YeastProtocol(Protocol):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/yeast"}
    )

    task: YeastTaskSpec = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["Protocol", "YeastProtocol"]}},
    )
    method: YeastMethodSpec = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["Protocol", "YeastProtocol"]}},
    )
    name: str = Field(
        default=...,
        description="""The name of the protocol.""",
        json_schema_extra={"linkml_meta": {"domain_of": ["Protocol"]}},
    )


class YeastLookResult(LookResult):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/yeast"}
    )

    p_hat: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": ["ArmMetrics", "BinomialArmMetrics", "YeastLookResult"]
            }
        },
    )
    z_score: float = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastLookResult"]}},
    )
    sample_n: Optional[int] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastLookResult"]}},
    )
    trajectory: Optional[list[float]] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastLookResult"]}},
    )
    efficacy_boundary: Optional[float] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastLookResult"]}},
    )
    raw_difference: Optional[float] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastLookResult"]}},
    )
    is_efficacy_crossed: Optional[bool] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastLookResult"]}},
    )
    status: Optional[str] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["YeastLookResult"]}},
    )
    look: Optional[int] = Field(
        default=None, json_schema_extra={"linkml_meta": {"domain_of": ["LookResult"]}}
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
YeastMethodSpec.model_rebuild()
YeastTaskSpec.model_rebuild()
YeastProtocol.model_rebuild()
YeastLookResult.model_rebuild()
