import os
import re
import sys


def fix_distributed_schema(method_name, tmp_dir, target_file):
    files = os.listdir(tmp_dir)
    primary_files = [
        f
        for f in files
        if f.endswith(".py")
        and f not in ["Base.py", "Binomial.py", "Continuous.py", "__init__.py"]
    ]

    if not primary_files:
        if "__init__.py" in files:
            primary_files = ["__init__.py"]
        else:
            print(f"No primary files found in {tmp_dir}")
            return

    merged_content = ""
    needed_base_imports = set()
    needed_binomial_imports = set()
    needed_continuous_imports = set()

    for pf in sorted(primary_files):
        with open(os.path.join(tmp_dir, pf), "r") as f:
            content = f.read()

            # Fix relative imports generated by datamodel-codegen
            for m in re.finditer(
                r"from \.(Base|Binomial|Continuous) import \((.*?)\)\n",
                content,
                flags=re.DOTALL,
            ):
                kind = m.group(1)
                names = [n.strip() for n in m.group(2).split(",")]
                if kind == "Base":
                    needed_base_imports.update(names)
                elif kind == "Binomial":
                    needed_binomial_imports.update(names)
                elif kind == "Continuous":
                    needed_continuous_imports.update(names)
            content = re.sub(
                r"from \.(Base|Binomial|Continuous) import \(.*?\)\n",
                "",
                content,
                flags=re.DOTALL,
            )

            for m in re.finditer(
                r"from \.(Base|Binomial|Continuous) import (.*?)\n", content
            ):
                kind = m.group(1)
                names = [n.strip() for n in m.group(2).split(",")]
                if kind == "Base":
                    needed_base_imports.update(names)
                elif kind == "Binomial":
                    needed_binomial_imports.update(names)
                elif kind == "Continuous":
                    needed_continuous_imports.update(names)
            content = re.sub(
                r"from \.(Base|Binomial|Continuous) import (.*?)\n", "", content
            )

            # Detect explicit Base.XXX references (e.g. arms: Base.ArmStructure)
            for m in re.finditer(r"(Base|Binomial|Continuous)\.(\w+)", content):
                kind = m.group(1)
                name = m.group(2)
                if kind == "Base":
                    needed_base_imports.add(name)
                elif kind == "Binomial":
                    needed_binomial_imports.add(name)
                elif kind == "Continuous":
                    needed_continuous_imports.add(name)

            # Replace these references with just the name
            content = re.sub(r"(Base|Binomial|Continuous)\.(\w+)", r"\2", content)

            # Remove local imports of the modules themselves
            content = re.sub(
                r"from \. import (Base|Binomial|Continuous)\n", "", content
            )

            merged_content += "\n" + content

    import_header = "from __future__ import annotations\n"
    if needed_base_imports:
        import_header += f"from earlysign.schema.ES3.Base import ({', '.join(sorted([n for n in needed_base_imports if n]))})\n"
    if needed_binomial_imports:
        import_header += f"from earlysign.schema.ES3.Binomial import ({', '.join(sorted([n for n in needed_binomial_imports if n]))})\n"
    if needed_continuous_imports:
        import_header += f"from earlysign.schema.ES3.Continuous import ({', '.join(sorted([n for n in needed_continuous_imports if n]))})\n"

    # Final cleanup
    merged_content = re.sub(r"from __future__ import annotations\n", "", merged_content)
    merged_content = re.sub(r"from enum import .*?\n", "", merged_content)
    merged_content = re.sub(r"from typing import .*?\n", "", merged_content)
    merged_content = re.sub(r"from pydantic import .*?\n", "", merged_content)
    merged_content = re.sub(r"from typing_extensions import .*?\n", "", merged_content)
    merged_content = re.sub(
        r"# generated by datamodel-codegen:.*?\n", "", merged_content, flags=re.DOTALL
    )
    merged_content = re.sub(r"#\s+filename:.*?\n", "", merged_content)

    # Re-add necessary standard imports once
    standard_imports = "from enum import StrEnum\nfrom typing import Annotated, Any, Literal, Union\nfrom pydantic import BaseModel, Field\nfrom typing_extensions import TypeAliasType\n"

    with open(target_file, "w") as f:
        f.write("# generated by datamodel-codegen via fix_distributed_schema.py\n")
        f.write(import_header)
        f.write(standard_imports)
        f.write("\n")
        f.write(merged_content.strip())
        f.write("\n")


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print(
            "Usage: python fix_distributed_schema.py <method_name> <tmp_dir> <target_file>"
        )
        sys.exit(1)
    fix_distributed_schema(sys.argv[1], sys.argv[2], sys.argv[3])
