# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel

from ..Base import (
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_1,
)


class AdaptationSpec(BaseModel):
    type: str


class Sided(StrEnum):
    ONE = "one"
    TWO = "two"


class TestStatistic(StrEnum):
    Z = "Z"
    CHI_SQUARE = "chi_square"
    EXACT = "exact"


class LinkFunction(StrEnum):
    IDENTITY = "identity"
    LOG = "log"
    LOGIT = "logit"


class BoundaryScale(StrEnum):
    Z_SCORE = "z_score"
    P_VALUE = "p_value"
    SCORE_STATISTIC = "score_statistic"


class TestStatisticModel(StrEnum):
    Z = "Z"
    T = "t"


class VarianceAssumption(StrEnum):
    KNOWN = "known"
    UNKNOWN = "unknown"
    HETEROSCEDASTIC = "heteroscedastic"


class EffectSizeSpec(BaseModel):
    """
    Numerical assumptions for the Alternative Hypothesis (H1).
    Note: This defines the "ball position" (simulation target), separate from the "goal posts" (Hypothesis Margins).
    """

    type: str


class EfficacyRequirement(BaseModel):
    """
    Efficacy requirement for group sequential design.
    Specifies the Type I error rate (alpha) to control.
    """

    alpha: float


class FutilityRequirement(BaseModel):
    """
    Futility requirement for group sequential design.
    Specifies the target power (1 - beta) and binding behavior.
    """

    power: float
    binding: bool | None = False


class HypothesisParameters(BaseModel):
    """
    Logical Margins and Test Objectives.
    """

    kind: str


class HypothesisSpec(BaseModel):
    h_null: str
    h_alt: str
    test_logic: HypothesisParameters
    target_effect: EffectSizeSpec


class NonInferiorityHypothesis(HypothesisParameters):
    kind: Literal["non_inferiority"] = "non_inferiority"
    non_inferiority_margin: float


class ReferenceModelSpec(BaseModel):
    """
    The "Core": Reference Model (Statistical Engine Assumptions).
    """

    kind: str


class Method(StrEnum):
    CONDITIONAL_POWER = "conditional_power"
    PREDICTIVE_POWER = "predictive_power"


class SampleSizeReestimationSpec(AdaptationSpec):
    type: Literal["sample_size_reestimation"] = "sample_size_reestimation"
    method: Method
    target_power: float
    n_range: list[Any]


class Unit(StrEnum):
    SAMPLE_SIZE = "sample_size"
    INFORMATION_FRACTION = "information_fraction"
    CALENDAR_TIME = "calendar_time"
    EVENTS = "events"


class ScheduleSpec(BaseModel):
    unit: Unit
    n_looks: int | None = None
    interim_points: list[float] | None = None


class SpendingFunctionType(StrEnum):
    """
    Available spending function types for group sequential design.
    """

    OBRIEN_FLEMING = "obrien_fleming"
    POCOCK = "pocock"
    KIM_DEMETS = "kim_demets"
    LAN_DEMETS = "lan_demets"
    POWER_FAMILY = "power_family"
    HWANG_SHIH_DECANI = "hwang_shih_decani"


class StoppingPolicyBase(BaseModel):
    """
    Abstract Base for Stopping Policy.
    """

    kind: str


class SuperiorityHypothesis(HypothesisParameters):
    kind: Literal["superiority"] = "superiority"
    superiority_margin: float


class SurvivalEffectSize(EffectSizeSpec):
    type: Literal["time_to_event"] = "time_to_event"
    hazard_ratios: dict[str, float]
    median_survival_times: dict[str, float] | None = None
    event_rate: float | None = None


class TestStatisticModel1(StrEnum):
    LOG_RANK = "log_rank"
    COX_PH = "cox_ph"


class SurvivalModel(ReferenceModelSpec):
    kind: Literal["time_to_event"] = "time_to_event"
    test_statistic: TestStatisticModel1
    use_canonical_joint_distribution: bool


class ResponseType(StrEnum):
    BINARY = "binary"
    CONTINUOUS = "continuous"
    TIME_TO_EVENT = "time_to_event"


class TaskSpec(TaskSpec_1):
    """
    GST-Specific Task Definition (Univariate).
    """

    kind: Literal["group_sequential"] = "group_sequential"
    arms: list[str]
    response_type: ResponseType
    hypotheses: HypothesisSpec
    efficacy: EfficacyRequirement | None = None
    futility: FutilityRequirement | None = None


class BinaryEffectSize(EffectSizeSpec):
    type: Literal["binary"] = "binary"
    proportions: dict[str, float]


class BinaryModel(ReferenceModelSpec):
    kind: Literal["binary"] = "binary"
    test_statistic: TestStatistic
    link_function: LinkFunction
    use_canonical_joint_distribution: bool


class BoundaryFunctionStoppingPolicyBase(StoppingPolicyBase):
    """
    Abstract Base for Shape-Based Boundary Policies.
    """


class BoundarySpec(BaseModel):
    """
    Abstract Base for a Boundary Definition.
    """

    kind: str
    reference_model: ReferenceModelSpec
    boundary_scale: BoundaryScale
    binding: bool


class ContinuousEffectSize(EffectSizeSpec):
    type: Literal["continuous"] = "continuous"
    means: dict[str, float]
    standard_deviation: float


class ContinuousModel(ReferenceModelSpec):
    kind: Literal["continuous"] = "continuous"
    test_statistic: TestStatisticModel
    variance_assumption: VarianceAssumption
    use_canonical_joint_distribution: bool


class CustomBoundary(BoundarySpec):
    kind: Literal["custom"] = "custom"
    values: list[float]


class EqualityHypothesis(HypothesisParameters):
    kind: Literal["equality"] = "equality"


class EquivalenceHypothesis(HypothesisParameters):
    kind: Literal["equivalence"] = "equivalence"
    lower_margin: float
    upper_margin: float


class FixedBoundary(BoundarySpec):
    kind: Literal["fixed"] = "fixed"
    value: float


class OBrienFlemingBoundaryPolicy(BoundaryFunctionStoppingPolicyBase):
    """
    Classic O'Brien-Fleming Policy.
    Shortcut for O'Brien-Fleming spending.
    """

    kind: Literal["obrien_fleming"] = "obrien_fleming"
    alpha: float
    sided: Sided


class PocockBoundaryPolicy(BoundaryFunctionStoppingPolicyBase):
    """
    Pocock Policy (Constant Boundary).
    """

    kind: Literal["pocock"] = "pocock"
    alpha: float
    sided: Sided


class SpendingFunctionSpec(BaseModel):
    family: SpendingFunctionType | str
    params: dict[str, float] | None = None


class SpendingFunctionStoppingPolicyBase(StoppingPolicyBase):
    """
    Abstract Base for Spending-Function Policies.
    """


class StoppingRule(BaseModel):
    schedule: ScheduleSpec
    boundary: BoundarySpec


class WangTsiatisBoundaryPolicy(BoundaryFunctionStoppingPolicyBase):
    """
    Wang-Tsiatis Power Family Policy.
    Parameterized by delta and alpha.
    """

    kind: Literal["wang_tsiatis"] = "wang_tsiatis"
    alpha: float
    delta: float
    sided: Sided


class WhiteheadBoundaryPolicy(BoundaryFunctionStoppingPolicyBase):
    """
    Whitehead's Triangular Test Policy.
    Typically defines both efficacy and futility boundaries.
    """

    kind: Literal["whitehead"] = "whitehead"
    alpha: float
    beta: float


class AlphaBetaSpendingPolicy(SpendingFunctionStoppingPolicyBase):
    """
    Combined Alpha-Beta Spending Policy.
    Efficacy (upper) + Futility (lower) boundaries.
    """

    kind: Literal["alpha_beta_spending"] = "alpha_beta_spending"
    alpha_spending_fn: SpendingFunctionSpec
    beta_spending_fn: SpendingFunctionSpec
    alpha_budget: float
    beta_budget: float
    alpha_binding: bool | None = True
    beta_binding: bool | None = False


class AlphaSpendingPolicy(SpendingFunctionStoppingPolicyBase):
    """
    Alpha (Efficacy) Spending Policy.
    Supports one-sided or two-sided tests.
    """

    kind: Literal["alpha_spending"] = "alpha_spending"
    spending_fn: SpendingFunctionSpec
    budget: float
    sided: Sided


class BetaSpendingPolicy(SpendingFunctionStoppingPolicyBase):
    """
    Beta (Futility) Spending Policy.
    Always one-sided (lower boundary).
    """

    kind: Literal["beta_spending"] = "beta_spending"
    spending_fn: SpendingFunctionSpec
    budget: float


class SpendingBoundary(BoundarySpec):
    kind: Literal["spending"] = "spending"
    spending_function: SpendingFunctionSpec


class StoppingPolicySpec(
    RootModel[
        AlphaSpendingPolicy
        | BetaSpendingPolicy
        | AlphaBetaSpendingPolicy
        | WhiteheadBoundaryPolicy
        | OBrienFlemingBoundaryPolicy
        | PocockBoundaryPolicy
        | WangTsiatisBoundaryPolicy
    ]
):
    root: (
        AlphaSpendingPolicy
        | BetaSpendingPolicy
        | AlphaBetaSpendingPolicy
        | WhiteheadBoundaryPolicy
        | OBrienFlemingBoundaryPolicy
        | PocockBoundaryPolicy
        | WangTsiatisBoundaryPolicy
    ) = Field(..., description="Discriminated Union for Stopping Policy types.")


class MethodSpec(MethodSpec_1):
    """
    GST-Specific Method Definition (Univariate).
    """

    kind: Literal["group_sequential"] = "group_sequential"
    stopping_policy: StoppingPolicySpec
    schedule: ScheduleSpec
    adaptation: AdaptationSpec | None = None


class Protocol(Protocol_1):
    """
    GST-Specific Protocol Container.
    Enforces that task and method belong to the GST domain.
    """

    task: TaskSpec
    method: MethodSpec
