# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel

from ..Base import (
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_1,
)


class AdaptationSpec(BaseModel):
    type: str


class Sided(StrEnum):
    ONE = "one"
    TWO = "two"


class LinkFunction(StrEnum):
    """
    Link function for the effect scale (Risk Difference, Risk Ratio, Odds Ratio).
    """

    IDENTITY = "identity"
    LOG = "log"
    LOGIT = "logit"


class VarianceAssumption(StrEnum):
    KNOWN = "known"
    ESTIMATED = "estimated"


class EffectSizeSpec(BaseModel):
    """
    Numerical assumptions for the Alternative Hypothesis (H1).
    Note: This defines the "ball position" (simulation target), separate from the "goal posts" (Hypothesis Margins).
    """

    type: str


class EfficacyRequirement(BaseModel):
    """
    Efficacy requirement for group sequential design.
    Specifies the Type I error rate (alpha) to control.
    """

    alpha: float


class FutilityRequirement(BaseModel):
    """
    Futility requirement for group sequential design.
    Specifies the target power (1 - beta) and binding behavior.
    """

    power: float = Field(..., description="Target Power (1 - Beta)")
    binding: bool | None = Field(
        False, description="Non-binding default (regulatory best practice)"
    )


class HypothesisParameters(BaseModel):
    """
    Logical Margins and Test Objectives.
    """

    kind: str


class HypothesisSpec(BaseModel):
    h_null: str
    h_alt: str
    test_logic: HypothesisParameters
    target_effect: EffectSizeSpec


class NonInferiorityHypothesis(HypothesisParameters):
    kind: Literal["non_inferiority"] = "non_inferiority"
    non_inferiority_margin: float


class Method(StrEnum):
    CONDITIONAL_POWER = "conditional_power"
    PREDICTIVE_POWER = "predictive_power"


class SampleSizeReestimationSpec(AdaptationSpec):
    type: Literal["sample_size_reestimation"] = "sample_size_reestimation"
    method: Method
    target_power: float
    n_range: list[Any]


class Unit(StrEnum):
    SAMPLE_SIZE = "sample_size"
    INFORMATION_FRACTION = "information_fraction"
    CALENDAR_TIME = "calendar_time"
    EVENTS = "events"


class ScheduleSpec(BaseModel):
    unit: Unit
    n_looks: int | None = Field(
        None, description="Usually defined by N looks and spacing, or specific points."
    )
    interim_points: list[float] | None = Field(
        None, description="Optional explicit points"
    )


class SpendingFunctionType(StrEnum):
    """
    Available spending function types for group sequential design.
    """

    OBRIEN_FLEMING = "obrien_fleming"
    POCOCK = "pocock"
    KIM_DEMETS = "kim_demets"
    LAN_DEMETS = "lan_demets"
    POWER_FAMILY = "power_family"
    HWANG_SHIH_DECANI = "hwang_shih_decani"


class StatisticalModel(BaseModel):
    """
    The "Model": Statistical Assumptions for Inference.The "Model": Statistical Assumptions for Inference.
    """

    kind: str


class SuperiorityHypothesis(HypothesisParameters):
    kind: Literal["superiority"] = "superiority"
    superiority_margin: float


class SurvivalEffectSize(EffectSizeSpec):
    type: Literal["time_to_event"] = "time_to_event"
    hazard_ratios: dict[str, float] = Field(
        ..., description="Arm name -> Hazard Ratio (relative to control)"
    )
    median_survival_times: dict[str, float] | None = Field(
        None, description="Optional: for sample size calc"
    )
    event_rate: float | None = Field(None, description="Overall event rate if needed")


class TProcessModel(StatisticalModel):
    kind: Literal["t_process"] = "t_process"
    degrees_of_freedom_method: str = Field(
        ..., description='Degrees of Freedom method (e.g., "satterthwaite")'
    )


class ResponseType(StrEnum):
    BINARY = "binary"
    CONTINUOUS = "continuous"
    TIME_TO_EVENT = "time_to_event"


class TaskSpec(TaskSpec_1):
    """
    GST-Specific Task Definition (Univariate).
    """

    kind: Literal["group_sequential"] = "group_sequential"
    arms: list[str]
    response_type: ResponseType
    hypotheses: HypothesisSpec
    efficacy: EfficacyRequirement | None = Field(
        None,
        description="Design Requirements (Designer Input)\nPresence implies the intent to stop for this reason.",
    )
    futility: FutilityRequirement | None = None


class TestStatisticSpec(BaseModel):
    """
    The "Statistic": Operational Definition of the Test Statistic.
    """

    kind: str


class TwoArmBinomialScoreZ(TestStatisticSpec):
    """
    Two-Arm Score Z-Statistic.
    """

    kind: Literal["two_arm_binomial_score_z"] = "two_arm_binomial_score_z"


class VarianceEstimation(StrEnum):
    """
    Variance estimation: pooled (common p) or unpooled.
    """

    POOLED = "pooled"
    UNPOOLED = "unpooled"


class TwoArmBinomialWaldZ(TestStatisticSpec):
    """
    Two-Arm Wald Z-Statistic.
    Computes Z = (p_t - p_c) / SE.
    """

    kind: Literal["two_arm_binomial_wald_z"] = "two_arm_binomial_wald_z"
    variance_estimation: VarianceEstimation = Field(
        ..., description="Variance estimation: pooled (common p) or unpooled."
    )


class BinaryEffectSize(EffectSizeSpec):
    type: Literal["binary"] = "binary"
    proportions: dict[str, float] = Field(..., description="Arm name -> Expected rate")


class BinomialExactStatistic(TestStatisticSpec):
    kind: Literal["binomial_exact"] = "binomial_exact"


class CanonicalGaussianModel(StatisticalModel):
    kind: Literal["canonical_gaussian"] = "canonical_gaussian"
    link_function: LinkFunction | None = Field(
        None,
        description="Link function for the effect scale (Risk Difference, Risk Ratio, Odds Ratio).",
    )


class ContinuousEffectSize(EffectSizeSpec):
    type: Literal["continuous"] = "continuous"
    means: dict[str, float] = Field(..., description="Arm name -> Expected mean")
    standard_deviation: float


class ContinuousWaldZ(TestStatisticSpec):
    kind: Literal["continuous_wald_z"] = "continuous_wald_z"
    variance_assumption: VarianceAssumption


class DecisionStrategyBase(BaseModel):
    """
    Abstract Base for Decision Strategy.
    Holds the Inferential Model (Assumption).
    """

    kind: str
    statistical_model: StatisticalModel


class EqualityHypothesis(HypothesisParameters):
    kind: Literal["equality"] = "equality"


class EquivalenceHypothesis(HypothesisParameters):
    kind: Literal["equivalence"] = "equivalence"
    lower_margin: float
    upper_margin: float


class ExactBinomialModel(StatisticalModel):
    kind: Literal["exact_binomial"] = "exact_binomial"


class OneArmBinomialWaldZ(TestStatisticSpec):
    """
    One-Arm Wald Z-Statistic.
    """

    kind: Literal["one_arm_binomial_wald_z"] = "one_arm_binomial_wald_z"


class SpendingFunction(BaseModel):
    family: SpendingFunctionType | str
    params: dict[str, float] | None = Field(
        None, description='e.g. { "rho": 2.0, "gamma": -4.0 }'
    )


class SpendingFunctionStrategyBase(DecisionStrategyBase):
    """
    Abstract Base for Spending-Function Strategies.
    """


class AlphaBetaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Combined Alpha-Beta Spending Strategy.
    """

    kind: Literal["alpha_beta_spending"] = "alpha_beta_spending"
    alpha_spending_fn: SpendingFunction
    beta_spending_fn: SpendingFunction
    alpha_budget: float
    beta_budget: float
    alpha_binding: bool | None = True
    beta_binding: bool | None = False


class AlphaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Alpha (Efficacy) Spending Strategy.
    """

    kind: Literal["alpha_spending"] = "alpha_spending"
    spending_fn: SpendingFunction
    budget: float
    sided: Sided


class BetaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Beta (Futility) Spending Strategy.
    """

    kind: Literal["beta_spending"] = "beta_spending"
    spending_fn: SpendingFunction
    budget: float


class BoundaryFunctionStrategyBase(DecisionStrategyBase):
    """
    Abstract Base for Shape-Based Boundary Strategies.
    """


class OBrienFlemingStrategy(BoundaryFunctionStrategyBase):
    """
    Classic O'Brien-Fleming Strategy.
    """

    kind: Literal["obrien_fleming"] = "obrien_fleming"
    alpha: float
    sided: Sided


class PocockStrategy(BoundaryFunctionStrategyBase):
    """
    Pocock Strategy.
    """

    kind: Literal["pocock"] = "pocock"
    alpha: float
    sided: Sided


class WangTsiatisStrategy(BoundaryFunctionStrategyBase):
    """
    Wang-Tsiatis Power Family Strategy.
    """

    kind: Literal["wang_tsiatis"] = "wang_tsiatis"
    alpha: float
    delta: float
    sided: Sided


class WhiteheadStrategy(BoundaryFunctionStrategyBase):
    """
    Whitehead's Triangular Test Strategy.
    """

    kind: Literal["whitehead"] = "whitehead"
    alpha: float
    beta: float


class DecisionStrategy(
    RootModel[
        AlphaSpendingStrategy
        | BetaSpendingStrategy
        | AlphaBetaSpendingStrategy
        | WhiteheadStrategy
        | OBrienFlemingStrategy
        | PocockStrategy
        | WangTsiatisStrategy
    ]
):
    root: (
        AlphaSpendingStrategy
        | BetaSpendingStrategy
        | AlphaBetaSpendingStrategy
        | WhiteheadStrategy
        | OBrienFlemingStrategy
        | PocockStrategy
        | WangTsiatisStrategy
    ) = Field(
        ..., description='Discriminated Union for Decision Strategies (The "Rule").'
    )


class StoppingPolicySpec(BaseModel):
    """
    Composite Policy Container.
    """

    statistic: TestStatisticSpec
    strategy: DecisionStrategy
    schedule: ScheduleSpec


class MethodSpec(MethodSpec_1):
    """
    GST-Specific Method Definition (Univariate).
    """

    kind: Literal["group_sequential"] = "group_sequential"
    stopping_policy: StoppingPolicySpec = Field(
        ..., description="Stopping Policy (discriminated union)"
    )
    adaptation: AdaptationSpec | None = None


class Protocol(Protocol_1):
    """
    GST-Specific Protocol Container.
    Enforces that task and method belong to the GST domain.
    """

    task: TaskSpec
    method: MethodSpec
