# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

from .. import Base
from ..Base import (
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_1,
)


class AdaptationSnapshot(BaseModel):
    """
    State captured during an adaptation event to preserve Type I error control.
    """

    z_t: float = Field(
        ..., description="Observed Z-statistic at the time of adaptation."
    )
    info_frac: float = Field(
        ..., description="Information fraction at the time of adaptation (t)."
    )
    original_max_sample_size: int = Field(
        ..., description="The maximum sample size before re-planning."
    )


class AdaptationSpec(BaseModel):
    type: str


class DecisionStrategyBase(BaseModel):
    """
    Abstract Base for Decision Strategy.
    Holds the Inferential Model (Assumption).
    """

    kind: str
    statistical_model: StatisticalModel


class BoundaryFunctionStrategyBase(DecisionStrategyBase):
    """
    Abstract Base for Shape-Based Boundary Strategies.
    """


class EffectMeasureBase(BaseModel):
    """
    Effect Measure for Binomial comparisons.
    """

    kind: str
    value: float


class AbsoluteDifference(EffectMeasureBase):
    kind: Literal["absolute_difference"] = "absolute_difference"


class EffectSizeSpecBase(BaseModel):
    """
    Numerical assumptions for the Alternative Hypothesis (H1).
    Note: This defines the "ball position" (simulation target), separate from the "goal posts" (Hypothesis Margins).
    """

    type: str


class BinaryEffectSize(EffectSizeSpecBase):
    type: Literal["binary"] = "binary"
    proportions: dict[str, float] = Field(..., description="Arm name -> Expected rate")


class ContinuousEffectSize(EffectSizeSpecBase):
    type: Literal["continuous"] = "continuous"
    means: dict[str, float] = Field(..., description="Arm name -> Expected mean")
    standard_deviation: float


class EfficacyRequirement(BaseModel):
    """
    Efficacy requirement for group sequential design.
    Specifies the Type I error rate (alpha) to control and binding behavior.
    """

    alpha: float
    binding: bool | None = Field(
        True, description="Binding (defaults to true: usually true for efficacy)."
    )


class FutilityRequirement(BaseModel):
    """
    Futility requirement for group sequential design.
    Specifies the target power (1 - beta) and binding behavior.
    """

    power: float = Field(..., description="Target Power (1 - Beta)")
    binding: bool | None = Field(
        False, description="Non-binding (defaults to false: regulatory best practice)"
    )


class HypothesisParametersBase(BaseModel):
    """
    Logical Margins and Test Objectives.
    """

    kind: str


class EqualityHypothesis(HypothesisParametersBase):
    kind: Literal["equality"] = "equality"


class EquivalenceHypothesis(HypothesisParametersBase):
    kind: Literal["equivalence"] = "equivalence"
    lower_margin: float
    upper_margin: float


class HypothesisSpec(BaseModel):
    h_null_description: str
    h_alt_description: str
    test_logic: HypothesisParameters
    target_effect: EffectSizeUnion


class InformationTimerBase(BaseModel):
    kind: str


class EventCountTimer(InformationTimerBase):
    kind: Literal["event_count"] = "event_count"
    max_events: int


class FisherInformationTimer(InformationTimerBase):
    kind: Literal["fisher_information"] = "fisher_information"
    max_information: float


class KnownVariance(BaseModel):
    """
    Shared Known Variance model.
    """

    kind: Literal["known"] = "known"
    value: float


class Method(StrEnum):
    CONDITIONAL_POWER = "conditional_power"
    PREDICTIVE_POWER = "predictive_power"


class MethodModel(StrEnum):
    """
    - "pooled": Equal variance assumption.
    - "unpooled": Unequal variance (Welch).
    """

    POOLED = "pooled"
    UNPOOLED = "unpooled"


class MethodSpec(MethodSpec_1):
    """
    GST-Specific Method Definition (Univariate).
    """

    kind: Literal["group_sequential"] = Field(
        "group_sequential", description="The kind of method (discriminator)."
    )
    stopping_policy: StoppingPolicySpec = Field(
        ..., description="Stopping Policy (discriminated union)."
    )
    adaptation: AdaptationSpec | None = Field(
        None, description="Technical specification for interim adaptation (SSR, etc.)."
    )
    adaptation_snapshot: AdaptationSnapshot | None = Field(
        None,
        description="Snapshot of internal state during adaptation, used for Weighted Z-score correction.",
    )


class NonInferiorityHypothesis(HypothesisParametersBase):
    kind: Literal["non_inferiority"] = "non_inferiority"
    non_inferiority_margin: float


class OBrienFlemingStrategy(BoundaryFunctionStrategyBase):
    """
    Classic O'Brien-Fleming Strategy.
    """

    kind: Literal["obrien_fleming"] = "obrien_fleming"
    alpha: float
    sided: Sided


class OddsRatio(EffectMeasureBase):
    kind: Literal["odds_ratio"] = "odds_ratio"


class OneArmEstimatedVariance(BaseModel):
    """
    One-Arm Variance options.
    """

    kind: Literal["estimated"] = "estimated"


OneArmContinuousVariance = TypeAliasType(
    "OneArmContinuousVariance", KnownVariance | OneArmEstimatedVariance
)


class PocockStrategy(BoundaryFunctionStrategyBase):
    """
    Pocock Strategy.
    """

    kind: Literal["pocock"] = "pocock"
    alpha: float
    sided: Sided


class Protocol(Protocol_1):
    """
    GST-Specific Protocol Container.
    Enforces that task and method belong to the GST domain.
    """

    task: TaskSpec = Field(..., description="The GST task specification.")
    method: MethodSpec = Field(..., description="The GST method specification.")


class RelativeRisk(EffectMeasureBase):
    kind: Literal["relative_risk"] = "relative_risk"


EffectMeasure = TypeAliasType(
    "EffectMeasure", AbsoluteDifference | OddsRatio | RelativeRisk
)


class ResponseType(StrEnum):
    BINARY = "binary"
    CONTINUOUS = "continuous"
    TIME_TO_EVENT = "time_to_event"


class SampleSizeReestimationSpec(AdaptationSpec):
    type: Literal["sample_size_reestimation"] = "sample_size_reestimation"
    method: Method
    target_power: float
    n_range: list[Any]


class SampleSizeTimer(InformationTimerBase):
    kind: Literal["sample_size"] = "sample_size"
    unit: Unit = Field(
        ...,
        description='"individuals": Count individuals (e.g. n1 + n2).\n"effective_size": Effective sample size (e.g. 4*n1*n2/(n1+n2)).',
    )
    max_sample_size: int


InformationTimer = TypeAliasType(
    "InformationTimer",
    Annotated[
        SampleSizeTimer | FisherInformationTimer | EventCountTimer,
        Field(..., description='Discriminated Union for Timer (The "Clock").'),
    ],
)


class ScheduleBase(BaseModel):
    kind: str


class EquidistantSchedule(ScheduleBase):
    kind: Literal["equidistant"] = "equidistant"
    n_looks: int


class FixedSchedule(ScheduleBase):
    kind: Literal["fixed"] = "fixed"
    analyses: list[float]


ScheduleSpec = TypeAliasType(
    "ScheduleSpec",
    Annotated[
        FixedSchedule | EquidistantSchedule,
        Field(..., description='Discriminated Union for Schedule (The "Checkpoints").'),
    ],
)


class Sided(StrEnum):
    ONE = "one"
    TWO = "two"


class SpendingFunction(BaseModel):
    family: SpendingFunctionType | str
    params: dict[str, float] | None = Field(
        None, description='e.g. { "rho": 2.0, "gamma": -4.0 }'
    )


class SpendingFunctionStrategyBase(DecisionStrategyBase):
    """
    Abstract Base for Spending-Function Strategies.
    """


class AlphaBetaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Combined Alpha-Beta Spending Strategy.
    """

    kind: Literal["alpha_beta_spending"] = "alpha_beta_spending"
    alpha_spending_fn: SpendingFunction
    beta_spending_fn: SpendingFunction
    alpha_budget: float
    beta_budget: float
    alpha_binding: bool | None = Field(
        True,
        description="Is the Alpha (Efficacy) boundary binding?\nIf True, crossing this boundary considers the trial stopped, providing slack for Beta calculations (fewer cases pass to the later stages for futility stopping, which reduces the false rejection cases, hence the boundary is less required to care the false rejection rate).",
    )
    beta_binding: bool | None = Field(
        False,
        description="Is the Beta (Futility) boundary binding?\nIf True, crossing this boundary considers the trial stopped, providing slack for Alpha calculations (fewer cases pass to the later stages for efficacy stopping, which reduces the false rejection cases, hence the boundary is less required to care the false rejection rate).",
    )


class AlphaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Alpha (Efficacy) Spending Strategy.
    """

    kind: Literal["alpha_spending"] = "alpha_spending"
    spending_fn: SpendingFunction
    budget: float
    sided: Sided


class BetaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Beta (Futility) Spending Strategy.
    """

    kind: Literal["beta_spending"] = "beta_spending"
    spending_fn: SpendingFunction
    budget: float


class SpendingFunctionType(StrEnum):
    """
    Available spending function types for group sequential design.
    """

    OBRIEN_FLEMING = "obrien_fleming"
    POCOCK = "pocock"
    POWER_FAMILY = "power_family"
    HWANG_SHIH_DECANI = "hwang_shih_decani"


class StatisticalModel(BaseModel):
    """
    The "Model": Statistical Assumptions for Inference.
    """

    kind: str


class CanonicalGaussianModel(StatisticalModel):
    kind: Literal["canonical_gaussian"] = "canonical_gaussian"


class ExactBinomialModel(StatisticalModel):
    kind: Literal["exact_binomial"] = "exact_binomial"


class StoppingPolicySpec(BaseModel):
    """
    Composite Policy Container.
    """

    statistic: TestStatisticSpec
    strategy: DecisionStrategy
    timer: InformationTimer
    schedule: ScheduleSpec
    trigger_strategy: TriggerStrategySpec | None = Field(
        default_factory=lambda: TriggerStrategySpec.model_validate(
            {"kind": "due_look", "tolerance": 0}
        ),
        description='Strategy for triggering interim analyses.\nDefaults to "due_look" (trigger when a milestone is reached).',
    )


class SuperiorityHypothesis(HypothesisParametersBase):
    kind: Literal["superiority"] = "superiority"
    superiority_margin: float


HypothesisParameters = TypeAliasType(
    "HypothesisParameters",
    EqualityHypothesis
    | SuperiorityHypothesis
    | NonInferiorityHypothesis
    | EquivalenceHypothesis,
)


class SurvivalEffectSize(EffectSizeSpecBase):
    type: Literal["time_to_event"] = "time_to_event"
    hazard_ratios: dict[str, float] = Field(
        ..., description="Arm name -> Hazard Ratio (relative to control)"
    )
    median_survival_times: dict[str, float] | None = Field(
        None, description="Optional: for sample size calc"
    )
    event_rate: float | None = Field(None, description="Overall event rate if needed")


EffectSizeUnion = TypeAliasType(
    "EffectSizeUnion", BinaryEffectSize | ContinuousEffectSize | SurvivalEffectSize
)


class TProcessModel(StatisticalModel):
    kind: Literal["t_process"] = "t_process"
    degrees_of_freedom_method: str = Field(
        ..., description='Degrees of Freedom method (e.g., "satterthwaite")'
    )


class TaskSpec(TaskSpec_1):
    """
    GST-Specific Task Definition (Univariate).
    """

    kind: Literal["group_sequential"] = "group_sequential"
    arms: Base.ArmStructure
    response_type: ResponseType
    hypotheses: HypothesisSpec
    efficacy: EfficacyRequirement | None = Field(
        None,
        description="Design Requirements (Designer Input)\nPresence implies the intent to stop for this reason.",
    )
    futility: FutilityRequirement | None = None


class TestStatisticSpec(BaseModel):
    """
    The "Statistic": Operational Definition of the Test Statistic.
    """

    kind: str


class BinomialExactStatistic(TestStatisticSpec):
    kind: Literal["binomial_exact"] = "binomial_exact"


class OneArmBinomialZ(TestStatisticSpec):
    """
    One-Arm Binomial Z-Statistic.
    """

    kind: Literal["one_arm_binomial_z"] = "one_arm_binomial_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance_source: VarianceSource = Field(
        ...,
        description='Variance source.\n- "sample": Uses observed estimate (Wald-like).\n- "null_hypothesis": Uses null parameter (Score-like).',
    )


class OneArmContinuousZ(TestStatisticSpec):
    """
    One-Arm Continuous Z-Statistic.
    """

    kind: Literal["one_arm_continuous_z"] = "one_arm_continuous_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance: OneArmContinuousVariance


class TriggerStrategySpecBase(BaseModel):
    kind: str


class DueLookTrigger(TriggerStrategySpecBase):
    """
    Triggers a look when a planned look is reached (due) and hasn't been analyzed.
    """

    kind: Literal["due_look"] = "due_look"
    tolerance: float | None = Field(
        0, description="Information time tolerance (e.g. 0.01 for 1% buffer)."
    )


class TriggerStrategySpec(DueLookTrigger):
    """
    Discriminated Union for Trigger Strategies.
    """


class TwoArmBinomialZ(TestStatisticSpec):
    """
    Two-Arm Binomial Z-Statistic.
    Covers both Wald Z (unpooled) and Score Z (pooled).
    """

    kind: Literal["two_arm_binomial_z"] = "two_arm_binomial_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance_estimation: VarianceEstimation = Field(
        ...,
        description='Variance estimation method.\n- "unpooled": Wald Z (Observed).\n- "pooled": Score Z (Null/Common).',
    )


class TwoArmContinuousZ(TestStatisticSpec):
    """
    Two-Arm Continuous Z-Statistic.
    """

    kind: Literal["two_arm_continuous_z"] = "two_arm_continuous_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance: TwoArmContinuousVariance


class TwoArmEstimatedVariance(BaseModel):
    """
    Two-Arm Variance options.
    """

    kind: Literal["estimated"] = "estimated"
    method: MethodModel = Field(
        ...,
        description='- "pooled": Equal variance assumption.\n- "unpooled": Unequal variance (Welch).',
    )


TwoArmContinuousVariance = TypeAliasType(
    "TwoArmContinuousVariance", KnownVariance | TwoArmEstimatedVariance
)


class Unit(StrEnum):
    """
    "individuals": Count individuals (e.g. n1 + n2).
    "effective_size": Effective sample size (e.g. 4*n1*n2/(n1+n2)).
    """

    INDIVIDUALS = "individuals"
    EFFECTIVE_SIZE = "effective_size"


class VarianceEstimation(StrEnum):
    """
    Variance estimation method.
    - "unpooled": Wald Z (Observed).
    - "pooled": Score Z (Null/Common).
    """

    POOLED = "pooled"
    UNPOOLED = "unpooled"


class VarianceSource(StrEnum):
    """
    Variance source.
    - "sample": Uses observed estimate (Wald-like).
    - "null_hypothesis": Uses null parameter (Score-like).
    """

    SAMPLE = "sample"
    NULL_HYPOTHESIS = "null_hypothesis"


class WangTsiatisStrategy(BoundaryFunctionStrategyBase):
    """
    Wang-Tsiatis Power Family Strategy.
    """

    kind: Literal["wang_tsiatis"] = "wang_tsiatis"
    alpha: float
    delta: float
    sided: Sided


class WhiteheadStrategy(BoundaryFunctionStrategyBase):
    """
    Whitehead's Triangular Test Strategy.
    """

    kind: Literal["whitehead"] = "whitehead"
    alpha: float
    beta: float


DecisionStrategy = TypeAliasType(
    "DecisionStrategy",
    Annotated[
        AlphaSpendingStrategy
        | BetaSpendingStrategy
        | AlphaBetaSpendingStrategy
        | WhiteheadStrategy
        | OBrienFlemingStrategy
        | PocockStrategy
        | WangTsiatisStrategy,
        Field(
            ..., description='Discriminated Union for Decision Strategies (The "Rule").'
        ),
    ],
)
