# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field

from ..Base import Log


class DecisionStatus(StrEnum):
    """
    Status of an ongoing or completed Group Sequential Test.
    """

    CONTINUE_ = "continue"
    STOP_EFFICACY = "stop_efficacy"
    STOP_FUTILITY = "stop_futility"
    STOP_PLAN_END_REACHED = "stop_plan_end_reached"
    STOP = "stop"


class LookResult(BaseModel):
    """
    Result of a statistical test/evaluation for the study at a look.
    """

    look: int | None = None
    sample_n: int
    info_frac: float
    z_stat: float
    efficacy_boundary: float | None = None
    is_efficacy_crossed: bool
    futility_boundary: float | None = None
    is_futility_crossed: bool
    status: DecisionStatus | str


class Trigger(BaseModel):
    """
    Defines the reason / cause for an operational event (e.g., Analysis Execution).
    """

    kind: str


class Analysis(Log):
    """
    Structural Record of a GST Analysis Execution.
    This captures the Context (Trigger), Metadata, and factual Result.
    """

    trigger: Trigger | None = None
    look: int = Field(..., description="Results")
    statistic: float
    info_frac: float
    decision: DecisionStatus | str
    efficacy_boundary: float | None = None
    futility_boundary: float | None = None


class Decision(Log):
    """
    Formalized Decision Event.
    """

    status: DecisionStatus | str
    message: str


class ManualTrigger(Trigger):
    """
    Triggered manually by a human operator.
    """

    kind: Literal["manual"] = "manual"
    reason: str


class ScheduleTrigger(Trigger):
    """
    Triggered by planned protocol milestones or schedules.
    """

    kind: Literal["schedule"] = "schedule"
    index: int
    value: float
