# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field

from ..Base import Log


class AdaptationLog(Log):
    """
    Log entry for an adaptation event (e.g., SSR).
    """

    look: int = Field(..., description="Look index at which adaptation was calculated.")
    conditional_power: float = Field(
        ..., description="Calculated conditional power based on current data."
    )
    promising_zone_status: PromisingZoneStatus | str = Field(
        ..., description="Status of the promising zone logic."
    )
    promising_zone_recommendation: str = Field(
        ..., description="Human-readable recommendation or message."
    )
    original_sample_size: int = Field(
        ..., description="Original planned max sample size."
    )
    recommended_sample_size: int | None = Field(
        None, description="Newly recommended max sample size (if SSR triggered)."
    )


class Analysis(Log):
    """
    Structural Record of a GST Analysis Execution.
    This captures the Context (Trigger), Metadata, and factual Result.
    """

    trigger: Trigger | None = None
    look: int = Field(..., description="Results")
    statistic: float
    info_frac: float
    decision: DecisionStatus | str
    efficacy_boundary: float | None = None
    futility_boundary: float | None = None


class Decision(Log):
    """
    Formalized Decision Event.
    """

    status: DecisionStatus | str
    message: str


class DecisionStatus(StrEnum):
    """
    Status of an ongoing or completed Group Sequential Test.
    """

    CONTINUE = "continue"
    STOP_EFFICACY = "stop_efficacy"
    STOP_FUTILITY = "stop_futility"
    STOP_PLAN_END_REACHED = "stop_plan_end_reached"
    STOP = "stop"


class LookResult(BaseModel):
    """
    Result of a statistical test/evaluation for the study at a look.
    """

    look: int | None = Field(None, description="Look index (1-indexed).")
    trigger: Trigger | None = Field(None, description="The trigger for this look.")
    sample_n: int = Field(..., description="Current cumulative sample size.")
    info_frac: float = Field(
        ..., description="Current fraction of information accrued."
    )
    z_stat: float = Field(..., description="Current calculated Z-statistic.")
    z_stats: dict[str, float] | None = Field(
        None, description="Dictionary of Z-statistics per arm (for MAMS)."
    )
    efficacy_boundary: float | None = Field(
        None, description="The calculated efficacy boundary at this look."
    )
    is_efficacy_crossed: bool = Field(
        ..., description="Whether the efficacy boundary was crossed."
    )
    futility_boundary: float | None = Field(
        None, description="The calculated futility boundary at this look."
    )
    is_futility_crossed: bool = Field(
        ..., description="Whether the futility boundary was crossed."
    )
    alpha_spent: float | None = Field(
        None, description="Cumulative Alpha spent up to this look."
    )
    beta_spent: float | None = Field(
        None, description="Cumulative Beta spent up to this look."
    )
    status: DecisionStatus | str = Field(
        ..., description="The decision status resulting from this look."
    )


class PromisingZoneStatus(StrEnum):
    FUTILITY = "futility"
    EFFICACY = "efficacy"
    PROMISING = "promising"
    CONTINUE = "continue"


class Trigger(BaseModel):
    """
    Defines the reason / cause for an operational event (e.g., Analysis Execution).
    """

    kind: str


class ManualTrigger(Trigger):
    """
    Triggered manually by a human operator.
    """

    kind: Literal["manual"] = "manual"
    reason: str


class ScheduleTrigger(Trigger):
    """
    Triggered by planned protocol milestones or schedules.
    """

    kind: Literal["schedule"] = "schedule"
    index: int
    value: float
