# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import Field

from ..Base import (
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_2,
)
from . import HypothesisSpec, TaskSpec as TaskSpec_1


class MultiplicityAdjustment(StrEnum):
    NONE = "none"
    BONFERRONI = "bonferroni"
    HOLM = "holm"
    HOCHBERG = "hochberg"
    GATEKEEPING = "gatekeeping"


class MethodSpec(MethodSpec_1):
    kind: Literal["group_sequential_multivariate"] = "group_sequential_multivariate"
    multiplicity_adjustment: MultiplicityAdjustment
    correlation_matrix: list[list[float]] | None = None


class TaskSpec(TaskSpec_2):
    """
    Multivariate Task (Multiple Endpoints).
    Composed of multiple Univariate GST Tasks.
    """

    kind: Literal["group_sequential_multivariate"] = "group_sequential_multivariate"
    sub_tasks: list[TaskSpec_1]
    arms: list[str]
    hypotheses: HypothesisSpec = Field(
        ...,
        description='Global Hypothesis (e.g., "At least one effective" or "Global Null").\nTypically represents the Union-Intersection or Intersection-Union test.',
    )
    alpha: float | None = None
    beta: float | None = None


class Protocol(Protocol_1):
    task: TaskSpec
    method: MethodSpec
