# Auto-generated by earlysign.parts.codegen.linkml_generator
# DO NOT EDIT MANUALLY
from enum import Enum
from typing import ClassVar, Literal, Optional, Union

from pydantic import (
    Field,
)

from earlysign.schema.ES3.Base import (
    ArmMetrics as ArmMetrics,
    ArmStatus as ArmStatus,
    ArmStructure as ArmStructure,
    ArmStructureBase as ArmStructureBase,
    ConfiguredBaseModel as ConfiguredBaseModel,
    LinkMLMeta as LinkMLMeta,
    Log as Log,
    LookResult as LookResult,
    Metadata as Metadata,
    MethodSpec as MethodSpec,
    MultiArmComparison as MultiArmComparison,
    Protocol as Protocol,
    Scoreboard as Scoreboard,
    SingleArm as SingleArm,
    TaskSpec as TaskSpec,
    TwoArmComparison as TwoArmComparison,
)
from earlysign.schema.ES3.Continuous import (
    CanonicalGaussianModel as CanonicalGaussianModel,
    ContinuousArmData as ContinuousArmData,
    ContinuousArmMetrics as ContinuousArmMetrics,
    EstimatedVariance as EstimatedVariance,
    KnownVariance as KnownVariance,
    Observation as Observation,
    TProcessModel as TProcessModel,
)

metamodel_version = "1.7.0"
version = "None"


class DecisionStatus(str, Enum):
    CONTINUE = "CONTINUE"
    STOP_EFFICACY = "STOP_EFFICACY"
    STOP_FUTILITY = "STOP_FUTILITY"
    STOP = "STOP"
    STOP_DETECTED = "STOP_DETECTED"
    STOP_PLAN_END_REACHED = "STOP_PLAN_END_REACHED"


class Sides(str, Enum):
    ONE = "ONE"
    TWO = "TWO"


class ResponseType(str, Enum):
    BINARY = "BINARY"
    CONTINUOUS = "CONTINUOUS"


class GAVIMethodSpec(MethodSpec):
    """
    MethodSpec for Generalized AVI.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/avi"}
    )

    burn_in: int = Field(
        default=100,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                ],
                "ifabsent": "int(100)",
            }
        },
    )
    kind: Literal["GAVI"] = Field(
        default="GAVI",
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "TaskSpec",
                    "MethodSpec",
                    "ArmStructureBase",
                    "SingleArm",
                    "TwoArmComparison",
                    "MultiArmComparison",
                    "CanonicalGaussianModel",
                    "TProcessModel",
                    "KnownVariance",
                    "EstimatedVariance",
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                    "AVITaskSpec",
                ],
                "equals_string": "GAVI",
                "ifabsent": "string(GAVI)",
            }
        },
    )
    alpha: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                ]
            }
        },
    )
    theta: float = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["GAVIMethodSpec"]}},
    )
    sides: Optional[Sides] = Field(
        default=Sides.TWO,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": ["GAVIMethodSpec", "MSPRTMethodSpec"],
                "ifabsent": "string(TWO)",
            }
        },
    )
    variance: Optional[float] = Field(
        default=None,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "ArmMetrics",
                    "ContinuousArmMetrics",
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                ]
            }
        },
    )
    max_n: Optional[int] = Field(
        default=None,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": ["GAVIMethodSpec", "SequentialQuantileMethodSpec"]
            }
        },
    )


class MSPRTMethodSpec(MethodSpec):
    """
    MethodSpec for mSPRT.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/avi"}
    )

    burn_in: int = Field(
        default=100,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                ],
                "ifabsent": "int(100)",
            }
        },
    )
    kind: Literal["MSPRT"] = Field(
        default="MSPRT",
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "TaskSpec",
                    "MethodSpec",
                    "ArmStructureBase",
                    "SingleArm",
                    "TwoArmComparison",
                    "MultiArmComparison",
                    "CanonicalGaussianModel",
                    "TProcessModel",
                    "KnownVariance",
                    "EstimatedVariance",
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                    "AVITaskSpec",
                ],
                "equals_string": "MSPRT",
                "ifabsent": "string(MSPRT)",
            }
        },
    )
    alpha: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                ]
            }
        },
    )
    tau: float = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["MSPRTMethodSpec"]}},
    )
    mde: Optional[float] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["MSPRTMethodSpec"]}},
    )
    sides: Optional[Sides] = Field(
        default=Sides.TWO,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": ["GAVIMethodSpec", "MSPRTMethodSpec"],
                "ifabsent": "string(TWO)",
            }
        },
    )
    variance: Optional[float] = Field(
        default=None,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "ArmMetrics",
                    "ContinuousArmMetrics",
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                ]
            }
        },
    )


class SequentialQuantileMethodSpec(MethodSpec):
    """
    MethodSpec for Sequential Quantile.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/avi"}
    )

    burn_in: int = Field(
        default=100,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                ],
                "ifabsent": "int(100)",
            }
        },
    )
    kind: Literal["SequentialQuantile"] = Field(
        default="SequentialQuantile",
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "TaskSpec",
                    "MethodSpec",
                    "ArmStructureBase",
                    "SingleArm",
                    "TwoArmComparison",
                    "MultiArmComparison",
                    "CanonicalGaussianModel",
                    "TProcessModel",
                    "KnownVariance",
                    "EstimatedVariance",
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                    "AVITaskSpec",
                ],
                "equals_string": "SequentialQuantile",
                "ifabsent": "string(SequentialQuantile)",
            }
        },
    )
    quantile: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {"domain_of": ["SequentialQuantileMethodSpec"]}
        },
    )
    alpha: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                ]
            }
        },
    )
    max_n: Optional[int] = Field(
        default=None,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": ["GAVIMethodSpec", "SequentialQuantileMethodSpec"]
            }
        },
    )


class AVITaskSpec(TaskSpec):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/avi"}
    )

    kind: Literal["avi"] = Field(
        default="avi",
        json_schema_extra={
            "linkml_meta": {
                "domain_of": [
                    "TaskSpec",
                    "MethodSpec",
                    "ArmStructureBase",
                    "SingleArm",
                    "TwoArmComparison",
                    "MultiArmComparison",
                    "CanonicalGaussianModel",
                    "TProcessModel",
                    "KnownVariance",
                    "EstimatedVariance",
                    "GAVIMethodSpec",
                    "MSPRTMethodSpec",
                    "SequentialQuantileMethodSpec",
                    "AVITaskSpec",
                ],
                "equals_string": "avi",
                "ifabsent": "string(avi)",
            }
        },
    )
    arms: ArmStructure = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["Scoreboard", "AVITaskSpec"]}},
    )
    response_type: Optional[ResponseType] = Field(
        default=ResponseType.CONTINUOUS,
        json_schema_extra={
            "linkml_meta": {
                "domain_of": ["AVITaskSpec"],
                "ifabsent": "string(CONTINUOUS)",
            }
        },
    )


AVIMethodSpec = Union[
    "GAVIMethodSpec", "MSPRTMethodSpec", "SequentialQuantileMethodSpec"
]


class AVIProtocol(Protocol):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/avi"}
    )

    task: AVITaskSpec = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["Protocol", "AVIProtocol"]}},
    )
    method: AVIMethodSpec = Field(
        default=...,
        json_schema_extra={"linkml_meta": {"domain_of": ["Protocol", "AVIProtocol"]}},
    )
    name: str = Field(
        default=...,
        description="""The name of the protocol.""",
        json_schema_extra={"linkml_meta": {"domain_of": ["Protocol"]}},
    )


class AVILookResult(LookResult):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/avi"}
    )

    sample_n: int = Field(
        default=..., json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}}
    )
    trajectory: float = Field(
        default=..., json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}}
    )
    boundary: Optional[float] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}},
    )
    is_crossed: Optional[bool] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}},
    )
    status: DecisionStatus = Field(
        default=..., json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}}
    )
    look: Optional[int] = Field(
        default=None, json_schema_extra={"linkml_meta": {"domain_of": ["LookResult"]}}
    )


class SequentialQuantileLookResult(AVILookResult):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://earlysign.io/schema/ES3/avi"}
    )

    estimated_quantile: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {"domain_of": ["SequentialQuantileLookResult"]}
        },
    )
    interval_lower: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {"domain_of": ["SequentialQuantileLookResult"]}
        },
    )
    interval_upper: float = Field(
        default=...,
        json_schema_extra={
            "linkml_meta": {"domain_of": ["SequentialQuantileLookResult"]}
        },
    )
    sample_n: int = Field(
        default=..., json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}}
    )
    trajectory: float = Field(
        default=..., json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}}
    )
    boundary: Optional[float] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}},
    )
    is_crossed: Optional[bool] = Field(
        default=None,
        json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}},
    )
    status: DecisionStatus = Field(
        default=..., json_schema_extra={"linkml_meta": {"domain_of": ["AVILookResult"]}}
    )
    look: Optional[int] = Field(
        default=None, json_schema_extra={"linkml_meta": {"domain_of": ["LookResult"]}}
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
GAVIMethodSpec.model_rebuild()
MSPRTMethodSpec.model_rebuild()
SequentialQuantileMethodSpec.model_rebuild()
AVITaskSpec.model_rebuild()
AVIProtocol.model_rebuild()
AVILookResult.model_rebuild()
SequentialQuantileLookResult.model_rebuild()
