id: https://earlysign.io/schema/ES3/avi
name: es3_avi
title: EarlySign AVI Method Schema

prefixes:
  linkml: https://w3id.org/linkml/
  base: https://earlysign.io/schema/ES3/base/

imports:
  - linkml:types
  - ../../schema/ES3/base
  - ../../schema/ES3/continuous

default_range: string
default_prefix: https://earlysign.io/schema/ES3/avi/

enums:

  DecisionStatus:
    permissible_values:
      CONTINUE: {}
      STOP_EFFICACY: {}
      STOP_FUTILITY: {}
      STOP: {}
      STOP_DETECTED: {}
      STOP_PLAN_END_REACHED: {}

  Sides:
    permissible_values:
      ONE: {}
      TWO: {}

  ResponseType:
    permissible_values:
      BINARY: {}
      CONTINUOUS: {}

classes:

  # -- Core extensions --

  GAVIMethodSpec:
    is_a: MethodSpec
    description: MethodSpec for Generalized AVI.
    attributes:
      burn_in:
        range: integer
        ifabsent: int(100)
        required: true
      kind:
        range: string
        equals_string: GAVI
        ifabsent: string(GAVI)
        required: true
      alpha:
        range: float
        required: true
      theta:
        range: float
        required: true
      sides:
        range: Sides
        ifabsent: string(TWO)
      variance:
        range: float
        required: false
      max_n:
        range: integer
        required: false

  MSPRTMethodSpec:
    is_a: MethodSpec
    description: MethodSpec for mSPRT.
    attributes:
      burn_in:
        range: integer
        ifabsent: int(100)
        required: true
      kind:
        range: string
        equals_string: MSPRT
        ifabsent: string(MSPRT)
        required: true
      alpha:
        range: float
        required: true
      tau:
        range: float
        required: true
      mde:
        range: float
        required: false
      sides:
        range: Sides
        ifabsent: string(TWO)
      variance:
        range: float
        required: false

  SequentialQuantileMethodSpec:
    is_a: MethodSpec
    description: MethodSpec for Sequential Quantile.
    attributes:
      burn_in:
        range: integer
        ifabsent: int(100)
        required: true
      kind:
        range: string
        equals_string: SequentialQuantile
        ifabsent: string(SequentialQuantile)
        required: true
      quantile:
        range: float
        required: true
      alpha:
        range: float
        required: true
      max_n:
        range: integer
        required: false

  # Specialized Task, Method (Union), and Protocol for AVI.
  
  AVITaskSpec:
    is_a: TaskSpec
    attributes:
      kind:
        range: string
        equals_string: avi
        ifabsent: string(avi)
        required: true
      arms:
        range: ArmStructure
        required: true
        inlined: true
      response_type:
        range: ResponseType
        ifabsent: string(CONTINUOUS)

  AVIMethodSpec:
    union_of:
      - GAVIMethodSpec
      - MSPRTMethodSpec
      - SequentialQuantileMethodSpec

  AVIProtocol:
    is_a: Protocol
    attributes:
      task:
        range: AVITaskSpec
        required: true
        inlined: true
      method:
        range: AVIMethodSpec
        required: true
        inlined: true

  # Specialized result Types
  AVILookResult:
    is_a: LookResult
    attributes:
      sample_n:
        range: integer
        required: true
      trajectory:
        range: float
        required: true
      boundary:
        range: float
        required: false
      is_crossed:
        range: boolean
        required: false
      status:
        range: DecisionStatus
        required: true

  SequentialQuantileLookResult:
    is_a: AVILookResult
    attributes:
      estimated_quantile:
        range: float
        required: true
      interval_lower:
        range: float
        required: true
      interval_upper:
        range: float
        required: true
