# generated by datamodel-codegen via fix_distributed_schema.py
from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

from earlysign.schema.ES3.Base import (
    ArmStructure,
    Log,
    MethodSpec as MethodSpec_1,
    Protocol as Protocol_1,
    TaskSpec as TaskSpec_1,
)


class AdaptationLog(Log):
    """
    Log entry for an adaptation event (e.g., SSR).
    """

    look: int = Field(..., description="Look index at which adaptation was calculated.")
    conditional_power: float = Field(
        ..., description="Calculated conditional power based on current data."
    )
    promising_zone_status: PromisingZoneStatus | str = Field(
        ..., description="Status of the promising zone logic."
    )
    promising_zone_recommendation: str = Field(
        ..., description="Human-readable recommendation or message."
    )
    original_sample_size: int = Field(
        ..., description="Original planned max sample size."
    )
    recommended_sample_size: int | None = Field(
        None, description="Newly recommended max sample size (if SSR triggered)."
    )


class AdaptationSnapshot(BaseModel):
    """
    State captured during an adaptation event to preserve Type I error control.
    """

    z_t: float = Field(
        ..., description="Observed Z-statistic at the time of adaptation."
    )
    info_frac: float = Field(
        ..., description="Information fraction at the time of adaptation (t)."
    )
    original_max_sample_size: int = Field(
        ..., description="The maximum sample size before re-planning."
    )
    use_weighted_statistic: bool | None = Field(
        True,
        description="Whether to use a weighted test statistic (e.g., Cui-Hung-Wang) after adaptation to preserve Type I error.",
    )


class AdaptationSpec(BaseModel):
    sample_size_reestimation: SampleSizeReestimationSpec | None = None


class Analysis(Log):
    """
    Structural Record of a GST Analysis Execution.
    This captures the Context (Trigger), Metadata, and factual Result.
    """

    trigger: Trigger | None = None
    look: int = Field(..., description="Results")
    statistic: float
    info_frac: float
    decision: DecisionStatus | str
    efficacy_boundary: float | None = None
    futility_boundary: float | None = None


class Decision(Log):
    """
    Formalized Decision Event.
    """

    status: DecisionStatus | str
    message: str


class DecisionStatus(StrEnum):
    """
    Status of an ongoing or completed Group Sequential Test.
    """

    CONTINUE = "continue"
    STOP_EFFICACY = "stop_efficacy"
    STOP_FUTILITY = "stop_futility"
    STOP_PLAN_END_REACHED = "stop_plan_end_reached"
    STOP = "stop"


class DecisionStrategyBase(BaseModel):
    """
    Abstract Base for Decision Strategy.
    Holds the Inferential Model (Assumption).
    """

    kind: str
    statistical_model: StatisticalModel


class BoundaryFunctionStrategyBase(DecisionStrategyBase):
    """
    Abstract Base for Shape-Based Boundary Strategies.
    """


class EffectMeasureBase(BaseModel):
    """
    Effect Measure for Binomial comparisons.
    """

    kind: str
    value: float


class AbsoluteDifference(EffectMeasureBase):
    kind: Literal["absolute_difference"] = "absolute_difference"


class EffectSizeSpecBase(BaseModel):
    """
    Numerical assumptions for the Alternative Hypothesis (H1).
    Note: This defines the "ball position" (simulation target), separate from the "goal posts" (Hypothesis Margins).
    """

    type: str


class BinaryEffectSize(EffectSizeSpecBase):
    type: Literal["binary"] = "binary"
    proportions: dict[str, float] = Field(..., description="Arm name -> Expected rate")


class ContinuousEffectSize(EffectSizeSpecBase):
    type: Literal["continuous"] = "continuous"
    means: dict[str, float] = Field(..., description="Arm name -> Expected mean")
    standard_deviation: float


class EfficacyRequirement(BaseModel):
    """
    Efficacy requirement for group sequential design.
    Specifies the Type I error rate (alpha) to control and binding behavior.
    """

    alpha: float
    binding: bool | None = Field(
        True, description="Binding (defaults to true: usually true for efficacy)."
    )


class FutilityRequirement(BaseModel):
    """
    Futility requirement for group sequential design.
    Specifies the target power (1 - beta) and binding behavior.
    """

    power: float = Field(..., description="Target Power (1 - Beta)")
    binding: bool | None = Field(
        False, description="Non-binding (defaults to false: regulatory best practice)"
    )


class HypothesisParametersBase(BaseModel):
    """
    Logical Margins and Test Objectives.
    """

    kind: str


class EqualityHypothesis(HypothesisParametersBase):
    kind: Literal["equality"] = "equality"


class EquivalenceHypothesis(HypothesisParametersBase):
    kind: Literal["equivalence"] = "equivalence"
    lower_margin: float
    upper_margin: float


class HypothesisSpec(BaseModel):
    h_null_description: str
    h_alt_description: str
    test_logic: HypothesisParameters
    target_effect: EffectSizeUnion


class InformationTimerBase(BaseModel):
    kind: str


class EventCountTimer(InformationTimerBase):
    kind: Literal["event_count"] = "event_count"
    max_events: int


class FisherInformationTimer(InformationTimerBase):
    kind: Literal["fisher_information"] = "fisher_information"
    max_information: float


class KnownVariance(BaseModel):
    """
    Shared Known Variance model.
    """

    kind: Literal["known"] = "known"
    value: float


class LookResult(BaseModel):
    """
    Result of a statistical test/evaluation for the study at a look.
    """

    look: int | None = Field(None, description="Look index (1-indexed).")
    trigger: Trigger | None = Field(None, description="The trigger for this look.")
    sample_n: int = Field(..., description="Current cumulative sample size.")
    info_frac: float = Field(
        ..., description="Current fraction of information accrued."
    )
    z_stat: float = Field(..., description="Current calculated Z-statistic.")
    z_stats: dict[str, float] | None = Field(
        None, description="Dictionary of Z-statistics per arm (for MAMS)."
    )
    efficacy_boundary: float | None = Field(
        None, description="The calculated efficacy boundary at this look."
    )
    is_efficacy_crossed: bool = Field(
        ..., description="Whether the efficacy boundary was crossed."
    )
    futility_boundary: float | None = Field(
        None, description="The calculated futility boundary at this look."
    )
    is_futility_crossed: bool = Field(
        ..., description="Whether the futility boundary was crossed."
    )
    alpha_spent: float | None = Field(
        None, description="Cumulative Alpha spent up to this look."
    )
    beta_spent: float | None = Field(
        None, description="Cumulative Beta spent up to this look."
    )
    status: DecisionStatus | str = Field(
        ..., description="The decision status resulting from this look."
    )


class Method(StrEnum):
    CONDITIONAL_POWER = "conditional_power"
    PREDICTIVE_POWER = "predictive_power"


class MethodModel(StrEnum):
    """
    - "pooled": Equal variance assumption.
    - "unpooled": Unequal variance (Welch).
    """

    POOLED = "pooled"
    UNPOOLED = "unpooled"


class MethodSpec(MethodSpec_1):
    """
    GST-Specific Method Definition (Univariate).
    """

    kind: Literal["group_sequential"] = Field(
        "group_sequential", description="The kind of method (discriminator)."
    )
    stopping_policy: StoppingPolicySpec = Field(
        ..., description="Stopping Policy (discriminated union)."
    )
    adaptation: AdaptationSpec | None = Field(
        None, description="Technical specification for interim adaptation (SSR, etc.)."
    )
    adaptation_snapshot: AdaptationSnapshot | None = Field(
        None,
        description="Snapshot of internal state during adaptation, used for Weighted Z-score correction.",
    )


class MultiplicityAdjustment(StrEnum):
    NONE = "none"
    BONFERRONI = "bonferroni"
    HOLM = "holm"
    HOCHBERG = "hochberg"
    GATEKEEPING = "gatekeeping"


class MultivariateMethodSpec(MethodSpec_1):
    kind: Literal["group_sequential_multivariate"] = "group_sequential_multivariate"
    multiplicity_adjustment: MultiplicityAdjustment
    correlation_matrix: list[list[float]] | None = None


class MultivariateProtocol(Protocol_1):
    task: MultivariateTaskSpec
    method: MultivariateMethodSpec


class MultivariateTaskSpec(TaskSpec_1):
    """
    Multivariate Task (Multiple Endpoints).
    Composed of multiple Univariate GST Tasks.
    """

    kind: Literal["group_sequential_multivariate"] = "group_sequential_multivariate"
    sub_tasks: list[TaskSpec] = Field(
        ..., description="Reusing the Standard GST TaskSpec"
    )
    arms: list[str] = Field(
        ...,
        description="Global parametersStudy-wide arms (must be consistent with sub_tasks)",
    )
    hypotheses: HypothesisSpec = Field(
        ...,
        description='Global Hypothesis (e.g., "At least one effective" or "Global Null").\nTypically represents the Union-Intersection or Intersection-Union test.',
    )
    alpha: float | None = Field(None, description="Global FWER")
    beta: float | None = Field(None, description="Global Power")


class NonInferiorityHypothesis(HypothesisParametersBase):
    kind: Literal["non_inferiority"] = "non_inferiority"
    non_inferiority_margin: float


class OBrienFlemingStrategy(BoundaryFunctionStrategyBase):
    """
    Classic O'Brien-Fleming Strategy.
    """

    kind: Literal["obrien_fleming"] = "obrien_fleming"
    alpha: float
    sided: Sided


class OddsRatio(EffectMeasureBase):
    kind: Literal["odds_ratio"] = "odds_ratio"


class OneArmEstimatedVariance(BaseModel):
    """
    One-Arm Variance options.
    """

    kind: Literal["estimated"] = "estimated"


OneArmContinuousVariance = TypeAliasType(
    "OneArmContinuousVariance", KnownVariance | OneArmEstimatedVariance
)


class PocockStrategy(BoundaryFunctionStrategyBase):
    """
    Pocock Strategy.
    """

    kind: Literal["pocock"] = "pocock"
    alpha: float
    sided: Sided


class PromisingZoneSpec(BaseModel):
    conditional_power_threshold_min: float
    conditional_power_threshold_max: float
    target_conditional_power: float


class PromisingZoneStatus(StrEnum):
    FUTILITY = "futility"
    EFFICACY = "efficacy"
    PROMISING = "promising"
    CONTINUE = "continue"


class Protocol(Protocol_1):
    """
    GST-Specific Protocol Container.
    Enforces that task and method belong to the GST domain.
    """

    task: TaskSpec = Field(..., description="The GST task specification.")
    method: MethodSpec = Field(..., description="The GST method specification.")


class RelativeImprovement(EffectMeasureBase):
    kind: Literal["relative_improvement"] = "relative_improvement"


class RelativeRisk(EffectMeasureBase):
    kind: Literal["relative_risk"] = "relative_risk"


EffectMeasure = TypeAliasType(
    "EffectMeasure", AbsoluteDifference | OddsRatio | RelativeRisk | RelativeImprovement
)


class ResponseType(StrEnum):
    BINARY = "binary"
    CONTINUOUS = "continuous"
    TIME_TO_EVENT = "time_to_event"


class SampleSizeReestimationSpec(BaseModel):
    type: Literal["sample_size_reestimation"] = "sample_size_reestimation"
    method: Method
    target_power: float
    use_weighted_statistic: bool | None = Field(
        True,
        description="Whether to use a weighted test statistic (e.g., Cui-Hung-Wang) after adaptation to preserve Type I error.",
    )
    n_range: list[Any]
    promising_zone: PromisingZoneSpec | None = Field(
        None, description="Promising zone configuration."
    )


class SampleSizeTimer(InformationTimerBase):
    kind: Literal["sample_size"] = "sample_size"
    unit: Unit = Field(
        ...,
        description='"individuals": Count individuals (e.g. n1 + n2).\n"effective_size": Effective sample size (e.g. 4*n1*n2/(n1+n2)).',
    )
    max_sample_size: dict[str, int] = Field(
        ..., description="The maximum sample size (per-arm)."
    )


InformationTimer = TypeAliasType(
    "InformationTimer",
    Annotated[
        SampleSizeTimer | FisherInformationTimer | EventCountTimer,
        Field(..., description='Discriminated Union for Timer (The "Clock").'),
    ],
)


class ScheduleBase(BaseModel):
    kind: str


class EquidistantSchedule(ScheduleBase):
    kind: Literal["equidistant"] = "equidistant"
    n_looks: int


class FixedSchedule(ScheduleBase):
    kind: Literal["fixed"] = "fixed"
    analyses: list[float]


ScheduleSpec = TypeAliasType(
    "ScheduleSpec",
    Annotated[
        FixedSchedule | EquidistantSchedule,
        Field(..., description='Discriminated Union for Schedule (The "Checkpoints").'),
    ],
)


class Sided(StrEnum):
    ONE = "one"
    TWO = "two"


class SpendingFunction(BaseModel):
    family: SpendingFunctionType | str
    params: dict[str, float] | None = Field(
        None, description='e.g. { "rho": 2.0, "gamma": -4.0 }'
    )


class SpendingFunctionStrategyBase(DecisionStrategyBase):
    """
    Abstract Base for Spending-Function Strategies.
    """


class AlphaBetaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Combined Alpha-Beta Spending Strategy.
    """

    kind: Literal["alpha_beta_spending"] = "alpha_beta_spending"
    alpha_spending_fn: SpendingFunction
    beta_spending_fn: SpendingFunction
    alpha_budget: float
    beta_budget: float
    alpha_binding: bool | None = Field(
        True,
        description="Is the Alpha (Efficacy) boundary binding?\nIf True, crossing this boundary considers the trial stopped, providing slack for Beta calculations (fewer cases pass to the later stages for futility stopping, which reduces the false rejection cases, hence the boundary is less required to care the false rejection rate).",
    )
    beta_binding: bool | None = Field(
        False,
        description="Is the Beta (Futility) boundary binding?\nIf True, crossing this boundary considers the trial stopped, providing slack for Alpha calculations (fewer cases pass to the later stages for efficacy stopping, which reduces the false rejection cases, hence the boundary is less required to care the false rejection rate).",
    )


class AlphaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Alpha (Efficacy) Spending Strategy.
    """

    kind: Literal["alpha_spending"] = "alpha_spending"
    spending_fn: SpendingFunction
    budget: float
    sided: Sided


class BetaSpendingStrategy(SpendingFunctionStrategyBase):
    """
    Beta (Futility) Spending Strategy.
    """

    kind: Literal["beta_spending"] = "beta_spending"
    spending_fn: SpendingFunction
    budget: float


class SpendingFunctionType(StrEnum):
    """
    Available spending function types for group sequential design.
    """

    OBRIEN_FLEMING = "obrien_fleming"
    POCOCK = "pocock"
    POWER_FAMILY = "power_family"
    HWANG_SHIH_DECANI = "hwang_shih_decani"


class StatisticalModel(BaseModel):
    """
    The "Model": Statistical Assumptions for Inference.
    """

    kind: str


class CanonicalGaussianModel(StatisticalModel):
    kind: Literal["canonical_gaussian"] = "canonical_gaussian"


class ExactBinomialModel(StatisticalModel):
    kind: Literal["exact_binomial"] = "exact_binomial"


class StoppingPolicySpec(BaseModel):
    """
    Composite Policy Container.
    """

    statistic: TestStatisticSpec
    strategy: DecisionStrategy
    timer: InformationTimer
    schedule: ScheduleSpec
    trigger_strategy: TriggerStrategySpec | None = Field(
        default_factory=lambda: TriggerStrategySpec.model_validate(
            {"kind": "due_look", "tolerance": 0}
        ),
        description='Strategy for triggering interim analyses.\nDefaults to "due_look" (trigger when a milestone is reached).',
    )


class SuperiorityHypothesis(HypothesisParametersBase):
    kind: Literal["superiority"] = "superiority"
    superiority_margin: float


HypothesisParameters = TypeAliasType(
    "HypothesisParameters",
    EqualityHypothesis
    | SuperiorityHypothesis
    | NonInferiorityHypothesis
    | EquivalenceHypothesis,
)


class SurvivalEffectSize(EffectSizeSpecBase):
    type: Literal["time_to_event"] = "time_to_event"
    hazard_ratios: dict[str, float] = Field(
        ..., description="Arm name -> Hazard Ratio (relative to control)"
    )
    median_survival_times: dict[str, float] | None = Field(
        None, description="Optional: for sample size calc"
    )
    event_rate: float | None = Field(None, description="Overall event rate if needed")


EffectSizeUnion = TypeAliasType(
    "EffectSizeUnion", BinaryEffectSize | ContinuousEffectSize | SurvivalEffectSize
)


class TProcessModel(StatisticalModel):
    kind: Literal["t_process"] = "t_process"
    degrees_of_freedom_method: str = Field(
        ..., description='Degrees of Freedom method (e.g., "satterthwaite")'
    )


class TaskSpec(TaskSpec_1):
    """
    GST-Specific Task Definition (Univariate).
    """

    kind: Literal["group_sequential"] = "group_sequential"
    arms: ArmStructure
    response_type: ResponseType
    hypotheses: HypothesisSpec
    efficacy: EfficacyRequirement | None = Field(
        None,
        description="Design Requirements (Designer Input)\nPresence implies the intent to stop for this reason.",
    )
    futility: FutilityRequirement | None = None


class TestStatisticSpec(BaseModel):
    """
    The "Statistic": Operational Definition of the Test Statistic.
    """

    kind: str


class BinomialExactStatistic(TestStatisticSpec):
    kind: Literal["binomial_exact"] = "binomial_exact"


class OneArmBinomialZ(TestStatisticSpec):
    """
    One-Arm Binomial Z-Statistic.
    """

    kind: Literal["one_arm_binomial_z"] = "one_arm_binomial_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance_source: VarianceSource = Field(
        ...,
        description='Variance source.\n- "sample": Uses observed estimate (Wald-like).\n- "null_hypothesis": Uses null parameter (Score-like).',
    )


class OneArmContinuousZ(TestStatisticSpec):
    """
    One-Arm Continuous Z-Statistic.
    """

    kind: Literal["one_arm_continuous_z"] = "one_arm_continuous_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance: OneArmContinuousVariance


class Trigger(BaseModel):
    """
    Defines the reason / cause for an operational event (e.g., Analysis Execution).
    """

    kind: str


class ManualTrigger(Trigger):
    """
    Triggered manually by a human operator.
    """

    kind: Literal["manual"] = "manual"
    reason: str


class ScheduleTrigger(Trigger):
    """
    Triggered by planned protocol milestones or schedules.
    """

    kind: Literal["schedule"] = "schedule"
    index: int
    value: float


class TriggerStrategySpecBase(BaseModel):
    kind: str


class DueLookTrigger(TriggerStrategySpecBase):
    """
    Triggers a look when a planned look is reached (due) and hasn't been analyzed.
    """

    kind: Literal["due_look"] = "due_look"
    tolerance: float | None = Field(
        0, description="Information time tolerance (e.g. 0.01 for 1% buffer)."
    )


class TriggerStrategySpec(DueLookTrigger):
    """
    Discriminated Union for Trigger Strategies.
    """


class TwoArmBinomialZ(TestStatisticSpec):
    """
    Two-Arm Binomial Z-Statistic.
    Covers both Wald Z (unpooled) and Score Z (pooled).
    """

    kind: Literal["two_arm_binomial_z"] = "two_arm_binomial_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance_estimation: VarianceEstimation = Field(
        ...,
        description='Variance estimation method.\n- "unpooled": Wald Z (Observed).\n- "pooled": Score Z (Null/Common).',
    )


class TwoArmContinuousZ(TestStatisticSpec):
    """
    Two-Arm Continuous Z-Statistic.
    """

    kind: Literal["two_arm_continuous_z"] = "two_arm_continuous_z"
    information_unit: Literal["fisher_information"] = "fisher_information"
    variance: TwoArmContinuousVariance


class TwoArmEstimatedVariance(BaseModel):
    """
    Two-Arm Variance options.
    """

    kind: Literal["estimated"] = "estimated"
    method: MethodModel = Field(
        ...,
        description='- "pooled": Equal variance assumption.\n- "unpooled": Unequal variance (Welch).',
    )


TwoArmContinuousVariance = TypeAliasType(
    "TwoArmContinuousVariance", KnownVariance | TwoArmEstimatedVariance
)


class Unit(StrEnum):
    """
    "individuals": Count individuals (e.g. n1 + n2).
    "effective_size": Effective sample size (e.g. 4*n1*n2/(n1+n2)).
    """

    INDIVIDUALS = "individuals"
    EFFECTIVE_SIZE = "effective_size"


class VarianceEstimation(StrEnum):
    """
    Variance estimation method.
    - "unpooled": Wald Z (Observed).
    - "pooled": Score Z (Null/Common).
    """

    POOLED = "pooled"
    UNPOOLED = "unpooled"


class VarianceSource(StrEnum):
    """
    Variance source.
    - "sample": Uses observed estimate (Wald-like).
    - "null_hypothesis": Uses null parameter (Score-like).
    """

    SAMPLE = "sample"
    NULL_HYPOTHESIS = "null_hypothesis"


class WangTsiatisStrategy(BoundaryFunctionStrategyBase):
    """
    Wang-Tsiatis Power Family Strategy.
    """

    kind: Literal["wang_tsiatis"] = "wang_tsiatis"
    alpha: float
    delta: float
    sided: Sided


class WhiteheadStrategy(BoundaryFunctionStrategyBase):
    """
    Whitehead's Triangular Test Strategy.
    """

    kind: Literal["whitehead"] = "whitehead"
    alpha: float
    beta: float


DecisionStrategy = TypeAliasType(
    "DecisionStrategy",
    Annotated[
        AlphaSpendingStrategy
        | BetaSpendingStrategy
        | AlphaBetaSpendingStrategy
        | WhiteheadStrategy
        | OBrienFlemingStrategy
        | PocockStrategy
        | WangTsiatisStrategy,
        Field(
            ..., description='Discriminated Union for Decision Strategies (The "Rule").'
        ),
    ],
)
