name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
      fail-fast: false  # 一つのバージョンが失敗しても他を継続
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          tool_versions: |
            python ${{ matrix.python-version }}
      - name: Install schema build dependencies
        run: |
          mise run compile-ES3
      - name: Run tests
        run: |
          mise run lint-type-test
